---
apiVersion: v1
kind: Service
metadata:
  name: kusionstack-controller-manager
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    control-plane: {{ .Values.controlPlane }}